---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time={{apt_cache_valid_time}}

- name: Update the configuration
  template:
    src: etc_apt_apt.conf.d_10general.j2
    dest: /etc/apt/apt.conf.d/10general
    owner: root
    group: root
    mode: 0644

- name: Make sure the required packages are installed
  apt: pkg={{item}} state=present
  with_items:
    - python-apt
    - python-pycurl
    - unattended-upgrades

- name: Append additional sources
  apt_repository: repo={{item}} update_cache=yes
  with_items: apt_repositories

- name: Install additional packages
  apt: pkg={{item}}
  with_items: apt_install_packages_list
  when: apt_install_packages

- name: Upgrade system
  apt: upgrade={{apt_upgrade}}
  when: apt_upgrade == "safe" or apt_upgrade == "full" or apt_upgrade == "dist"
